name: .NET Core Desktop Release

on:
  push:
   branches: ["main"]
    tags:
      - 'v*' # Si attiva solo al push di un tag (es. git push origin v1.0.0)

permissions:
  contents: write # Permesso fondamentale per creare la Release su GitHub

jobs:
  build-and-release:
    runs-on: windows-latest

    env:
      Solution_Name: FormatoFogliSpesa.slnx
      Wap_Project_Directory: ./
      Wap_Project_Path: .\FormatoFogliSpesa\FormatoFogliSpesa.csproj
      Configuration: Release # Fissato su Release per la versione finale

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration

    - name: Decode the pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path $env
